// Code generated by trpc-go/trpc-go-cmdline v2.9.12. DO NOT EDIT.
// source: user.proto

package user

import (
	"context"
	"errors"
	"fmt"

	_ "git.code.oa.com/trpc-go/trpc-go"
	"git.code.oa.com/trpc-go/trpc-go/client"
	"git.code.oa.com/trpc-go/trpc-go/codec"
	_ "git.code.oa.com/trpc-go/trpc-go/http"
	"git.code.oa.com/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// UserServiceService defines service.
type UserServiceService interface {
	CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRsp, error)

	GetUser(ctx context.Context, req *GetUserReq) (*GetUserRsp, error)
}

func UserServiceService_CreateUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateUserReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).CreateUser(ctx, reqbody.(*CreateUserReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func UserServiceService_GetUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetUserReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(UserServiceService).GetUser(ctx, reqbody.(*GetUserReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// UserServiceServer_ServiceDesc descriptor for server.RegisterService.
var UserServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.study.user.UserService",
	HandlerType: ((*UserServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.study.user.UserService/CreateUser",
			Func: UserServiceService_CreateUser_Handler,
		},
		{
			Name: "/trpc.study.user.UserService/GetUser",
			Func: UserServiceService_GetUser_Handler,
		},
	},
}

// RegisterUserServiceService registers service.
func RegisterUserServiceService(s server.Service, svr UserServiceService) {
	if err := s.Register(&UserServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("UserService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedUserService struct{}

func (s *UnimplementedUserService) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRsp, error) {
	return nil, errors.New("rpc CreateUser of service UserService is not implemented")
}
func (s *UnimplementedUserService) GetUser(ctx context.Context, req *GetUserReq) (*GetUserRsp, error) {
	return nil, errors.New("rpc GetUser of service UserService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// UserServiceClientProxy defines service client proxy
type UserServiceClientProxy interface {
	CreateUser(ctx context.Context, req *CreateUserReq, opts ...client.Option) (rsp *CreateUserRsp, err error)

	GetUser(ctx context.Context, req *GetUserReq, opts ...client.Option) (rsp *GetUserRsp, err error)
}

type UserServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewUserServiceClientProxy = func(opts ...client.Option) UserServiceClientProxy {
	return &UserServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *UserServiceClientProxyImpl) CreateUser(ctx context.Context, req *CreateUserReq, opts ...client.Option) (*CreateUserRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.study.user.UserService/CreateUser")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("study")
	msg.WithCalleeServer("user")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("CreateUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateUserRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *UserServiceClientProxyImpl) GetUser(ctx context.Context, req *GetUserReq, opts ...client.Option) (*GetUserRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.study.user.UserService/GetUser")
	msg.WithCalleeServiceName(UserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("study")
	msg.WithCalleeServer("user")
	msg.WithCalleeService("UserService")
	msg.WithCalleeMethod("GetUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetUserRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
