// Code generated by MockGen. DO NOT EDIT.
// Source: user.trpc.go

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	client "git.code.oa.com/trpc-go/trpc-go/client"
	gomock "github.com/golang/mock/gomock"
)

// MockUserServiceService is a mock of UserServiceService interface.
type MockUserServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceServiceMockRecorder
}

// MockUserServiceServiceMockRecorder is the mock recorder for MockUserServiceService.
type MockUserServiceServiceMockRecorder struct {
	mock *MockUserServiceService
}

// NewMockUserServiceService creates a new mock instance.
func NewMockUserServiceService(ctrl *gomock.Controller) *MockUserServiceService {
	mock := &MockUserServiceService{ctrl: ctrl}
	mock.recorder = &MockUserServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceService) EXPECT() *MockUserServiceServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserServiceService) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req)
	ret0, _ := ret[0].(*CreateUserRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceServiceMockRecorder) CreateUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServiceService)(nil).CreateUser), ctx, req)
}

// GetUser mocks base method.
func (m *MockUserServiceService) GetUser(ctx context.Context, req *GetUserReq) (*GetUserRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, req)
	ret0, _ := ret[0].(*GetUserRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceServiceMockRecorder) GetUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserServiceService)(nil).GetUser), ctx, req)
}

// MockGatewayServiceService is a mock of GatewayServiceService interface.
type MockGatewayServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayServiceServiceMockRecorder
}

// MockGatewayServiceServiceMockRecorder is the mock recorder for MockGatewayServiceService.
type MockGatewayServiceServiceMockRecorder struct {
	mock *MockGatewayServiceService
}

// NewMockGatewayServiceService creates a new mock instance.
func NewMockGatewayServiceService(ctrl *gomock.Controller) *MockGatewayServiceService {
	mock := &MockGatewayServiceService{ctrl: ctrl}
	mock.recorder = &MockGatewayServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayServiceService) EXPECT() *MockGatewayServiceServiceMockRecorder {
	return m.recorder
}

// GreetUser mocks base method.
func (m *MockGatewayServiceService) GreetUser(ctx context.Context, req *GreetUserReq) (*GreetUserRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GreetUser", ctx, req)
	ret0, _ := ret[0].(*GreetUserRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GreetUser indicates an expected call of GreetUser.
func (mr *MockGatewayServiceServiceMockRecorder) GreetUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GreetUser", reflect.TypeOf((*MockGatewayServiceService)(nil).GreetUser), ctx, req)
}

// MockUserServiceClientProxy is a mock of UserServiceClientProxy interface.
type MockUserServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceClientProxyMockRecorder
}

// MockUserServiceClientProxyMockRecorder is the mock recorder for MockUserServiceClientProxy.
type MockUserServiceClientProxyMockRecorder struct {
	mock *MockUserServiceClientProxy
}

// NewMockUserServiceClientProxy creates a new mock instance.
func NewMockUserServiceClientProxy(ctrl *gomock.Controller) *MockUserServiceClientProxy {
	mock := &MockUserServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockUserServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceClientProxy) EXPECT() *MockUserServiceClientProxyMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserServiceClientProxy) CreateUser(ctx context.Context, req *CreateUserReq, opts ...client.Option) (*CreateUserRsp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateUser", varargs...)
	ret0, _ := ret[0].(*CreateUserRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceClientProxyMockRecorder) CreateUser(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServiceClientProxy)(nil).CreateUser), varargs...)
}

// GetUser mocks base method.
func (m *MockUserServiceClientProxy) GetUser(ctx context.Context, req *GetUserReq, opts ...client.Option) (*GetUserRsp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUser", varargs...)
	ret0, _ := ret[0].(*GetUserRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceClientProxyMockRecorder) GetUser(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserServiceClientProxy)(nil).GetUser), varargs...)
}

// MockGatewayServiceClientProxy is a mock of GatewayServiceClientProxy interface.
type MockGatewayServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayServiceClientProxyMockRecorder
}

// MockGatewayServiceClientProxyMockRecorder is the mock recorder for MockGatewayServiceClientProxy.
type MockGatewayServiceClientProxyMockRecorder struct {
	mock *MockGatewayServiceClientProxy
}

// NewMockGatewayServiceClientProxy creates a new mock instance.
func NewMockGatewayServiceClientProxy(ctrl *gomock.Controller) *MockGatewayServiceClientProxy {
	mock := &MockGatewayServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockGatewayServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayServiceClientProxy) EXPECT() *MockGatewayServiceClientProxyMockRecorder {
	return m.recorder
}

// GreetUser mocks base method.
func (m *MockGatewayServiceClientProxy) GreetUser(ctx context.Context, req *GreetUserReq, opts ...client.Option) (*GreetUserRsp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GreetUser", varargs...)
	ret0, _ := ret[0].(*GreetUserRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GreetUser indicates an expected call of GreetUser.
func (mr *MockGatewayServiceClientProxyMockRecorder) GreetUser(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GreetUser", reflect.TypeOf((*MockGatewayServiceClientProxy)(nil).GreetUser), varargs...)
}
